# Cloudflare Pages 配置文件

# 构建配置
[build]
  command = "npm run build"
  publish = "dist"

# 环境变量
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# 页面规则
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# 函数配置
[functions]
  directory = "functions"

# 开发环境
[env.development]
  R2_BUCKET_NAME = "mannix-dev"

# 生产环境  
[env.production]
  R2_BUCKET_NAME = "mannix"

# 预览环境
[env.preview]
  R2_BUCKET_NAME = "mannix-preview"
