name = "r2-dashboard"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
DRAFT_DOMAIN = "https://oss.mannix.fun"
PORT = "8787"

# R2 存储桶绑定
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "mannix"

# 环境变量 (在 Cloudflare Dashboard 中设置敏感信息)
# R2_ACCESS_KEY_ID = "your_access_key_id"
# R2_ACCESS_KEY_SECRET = "your_access_key_secret"
# R2_ENDPOINT = "your_r2_endpoint"
# R2_BUCKET_NAME = "mannix"

[build]
command = "npm run build"

# 开发环境配置
[env.development]
name = "r2-dashboard-dev"

[env.development.vars]
NODE_ENV = "development"

# 生产环境配置
[env.production]
name = "r2-dashboard-prod"

[env.production.vars]
NODE_ENV = "production"

# KV 命名空间（如果需要缓存功能）
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your_kv_namespace_id"

# Durable Objects（如果需要）
# [[durable_objects.bindings]]
# name = "R2_SESSIONS"
# class_name = "SessionManager"
