# Cloudflare Pages 专用配置
# 使用此配置部署到 Pages，避免 Workers 相关的静态文件问题

name = "r2-dashboard-pages"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages 项目类型
pages_build_output_dir = "dist"

# R2 绑定配置
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "mannix"

# 环境变量
[vars]
R2_BUCKET_NAME = "mannix"
DRAFT_DOMAIN = "https://oss.mannix.fun"

# 开发环境配置
[env.development]
[env.development.vars]
R2_BUCKET_NAME = "mannix"
DRAFT_DOMAIN = "https://oss.mannix.fun"

# 生产环境配置
[env.production]
[env.production.vars]
R2_BUCKET_NAME = "mannix"
DRAFT_DOMAIN = "https://oss.mannix.fun"
